"""Build a self-contained agent using Node.js built-ins only."""
from pathlib import Path
root = Path(__file__).resolve().parent
files = ['quota-format.js', 'rate-limits.js', 'display-values.js', 'app-server.js',
         'injected-ui.js', 'project-colors.js', 'project-sizes-ui.js', 'thread-tokens-ui.js', 'cdp.js',
         'resolve.js', 'thread-token-reader.js', 'project-size-reader.js', 'agent-main.js']
source = '// Generated by build.py. MIT License. See LICENSE.\n\"use strict\";\n'
source += '\n'.join((root / 'src' / name).read_text(encoding='utf-8') for name in files)
(root / 'agent.cjs').write_text(source, encoding='utf-8')
print('Built agent.cjs (no bundled third-party runtime dependencies)')
